version: '3.7'
services:
  unittest:
    build:
      context: ./
      dockerfile: Dockerfile.unittest
  pack:
    build:
      context: ./
      dockerfile: Dockerfile.build
      args:
        - RELEASE_VERSION
