name: Build, Test and Release
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.nbgv.outputs.SemVer2 }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: NBGV
        id: nbgv
        uses: dotnet/nbgv@master
        with:
          setAllVars: true
          setCommonVars: true

      - name: Build
        run: |
          export RELEASE_VERSION="${{ env.NBGV_SemVer2 }}"
          docker-compose build --progress plain pack

      - name: Create Artifact
        run: |
          export RELEASE_VERSION="${{ env.NBGV_SemVer2 }}"
          docker create -ti --name configenv configenv_pack bash
          docker cp configenv:/build/ConfigEnv/bin/Release/ConfigEnv.${RELEASE_VERSION}.nupkg ConfigEnv.${RELEASE_VERSION}.nupkg
          docker rm configenv

      - uses: actions/upload-artifact@master
        with:
          name: ConfigEnv
          path: '*.nupkg'

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit Test
        run: |
          docker-compose build --progress plain unittest

  release:
    needs: [build, test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@master
        with:
          name: ConfigEnv

      - name: NuGet Release
        run: |
          dotnet nuget push "ConfigEnv.${{ needs.build.outputs.version }}.nupkg" --api-key ${{ secrets.NUGET_TOKEN }} --source nuget.org
