name: Build
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          docker-compose build --progress plain pack
      - name: Set Release Version
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo $GITHUB_ENV
          cat $GITHUB_ENV
          echo $GITHUB_REF
      - name: Store Artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          ls -la
          docker create -ti --name configenv configenv_pack bash
          docker cp configenv:/build/ConfigEnv/bin/Release/ConfigEnv.1.0.0.nupkg ConfigEnv.1.0.0.nupkg
          docker rm configenv
      - uses: actions/upload-artifact@master
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          name: ConfigEnv.1.0.0.nupkg
          path: ConfigEnv.1.0.0.nupkg
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit Test
        run: |
          docker-compose build --progress plain unittest
  release:
    needs: [build, test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: ConfigEnv.1.0.0.nupkg
      - name: Release
        run: |
          ls -la
          dotnet nuget push "ConfigEnv.1.0.0.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/daidnoggin/index.json"
